[package]

name = "gol-rust"
version = "0.0.1"
authors = ["Tony Lukasavage <anthony.lukasavage@gmail.com>"]

[dependencies.gfx]

git = "http://github.com/gfx-rs/gfx-rs"

[dependencies.glutin]

git = "https://github.com/tomaka/glutin"